version: '3'
services:
  frontend:
    image: agustinadiaz/react-nginx-app:latest  # La imagen que subiste a Docker Hub
    ports:
      - "80:80"  # El frontend se ejecutar치 en el puerto 80
    depends_on:
      - backend  # El frontend depende del backend

  backend:
    build: ./  # Esto construir치 el backend desde el Dockerfile localmente
    ports:
      - "8001:8000"  # El backend estar치 accesible en el puerto 8000
    volumes:
      - .:/app  # Mantener el c칩digo en la carpeta app
    environment:
      FLASK_ENV: development